# Config file for automatic testing at travis-ci.org

language: python
dist: "xenial"
python:
  - 3.7
  - 3.6
  - 3.5
  - 3.4

stages:
  - lint
  - test
  - name: deploy
    if: tag IS present

before_install:
  - pip install --upgrade pip
install:
  - pip install poetry
  - pip install tox-travis
script:
  - tox

jobs:
  include:
    - stage: lint
      python: 3.6
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files
    - stage: deploy
      script:
        - echo Deploying to PyPI...
      before_deploy:
        # User and password environment variables are set as hidden variables through
        # the web interface in the project settings.
        - pip install --upgrade pip
        - pip install poetry
        - poetry config http-basic.pypi $PYPI_USER $PYPI_PASS
        - poetry build
      deploy:
        provider: script
        script: poetry publish
        skip_cleanup: true
        on:
          branch: master
          tags: true
