[tool.poetry]
name = "py-wave-runup"
version = "0.1.0"
description = "Empirical wave runup models implemented in Python"
authors = ["Chris Leaman"]
license = "GPL-3.0+"

[tool.poetry.dependencies]
python = "~2.7 || ^3.4 || ^3.5 || ^3.6 || ^3.7"
numpy = "^1.16"

[tool.poetry.dev-dependencies]
tox = "^3.8"
coverage = "^4.5"
pytest-runner = "^4.4"
pytest = "^4.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
